petitions/config/routes.rb
Rails.application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "petitions#index"

  resources :users
  resources :sessions
  resources :petitions 
  resources :votes, only: :create

end

petitions/app/models/petition.rb
class Petition < ActiveRecord::Base

  belongs_to :user
  has_many :votes

  DAYS_BEFORE_EXPIRE = 30.day.ago 

  def expired?(created_at)
  	created_at < DAYS_BEFORE_EXPIRE
  end

  def voted_by?(user)
    votes.where(user_id: user.id).any?
  end
end

petitions/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :email, :password, on: :create
  validates_uniqueness_of :email

  has_many :petitions
  has_many :votes

  def encrypt_password
  	if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

	def self.auth(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
   		user
 	  else
    	nil
  	end
	end
end

petitions/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition

  validates :user_id, uniqueness: { scope: :petition_id }

  VOTES_MAX = 100

end

petitions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to sign_up_url, alert: 'Вы не авторизованы' if current_user.nil?
  end
end

petitions/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

petitions/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :authorize, only: [:new, :create]

  def index
    @petitions = Petition.all
    @petitions = @petitions.where(user: current_user) if params[:my]
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def edit
    @petition = current_user.petitions.find(params[:id])
    if @petition.expired?(@petition.created_at)
      flash["alert-danger"] = 'Петиция закрыта'
      redirect_to petitions_path(my: true)
    else
      @petition
    end
  end

  def update
    petition = current_user.petitions.find(params[:id])
    petition.update(petition_params)
    flash["alert-success"] = 'Петиция обновлена'
    redirect_to petition
  end

  def create
    petition = current_user.petitions.create(petition_params)
    redirect_to petition
  end

  def new
    @petition = Petition.new
  end

  def destroy
    petition = current_user.petitions.find(params[:id])
    petition.destroy
    flash["alert-success"] = 'Петиция удалена'
    redirect_to petitions_path
  end

  private

  def petition_params
    params.require(:petition).permit(:title, :text)
  end
end

petitions/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.auth(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash["alert-success"] = "Добро Пожаловать #{user.first_name}"
      redirect_to root_url
    else
      flash["alert-danger"] = "Неверный email или пароль"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash["alert-success"] = "Пока-пока"
    redirect_to root_url
  end
end

petitions/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      flash["alert-success"] = "Добро Пожаловать"
      redirect_to root_url
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

petitions/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authorize

  def create
    vote = current_user.votes.create(permitted_params)
    votes = Vote.where(permitted_params).count
    if votes >= Vote::VOTES_MAX
      petition = vote.petition
      UserMailer.votes_recruited(petition, votes).deliver_later
      UserMailer.admin_votes_recruited(petition, votes).deliver_later
    end
    flash["alert-success"] = 'Спасибо! Ваш голос учтен'
    redirect_to vote.petition
  end

  def permitted_params
    params.permit(:petition_id)
  end
end

petitions/app/helpers/application_helper.rb
module ApplicationHelper

def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
end

def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

petitions/app/helpers/home_helper.rb
module HomeHelper
end

petitions/app/helpers/petitions_helper.rb
module PetitionsHelper
end

petitions/app/helpers/sessions_helper.rb
module SessionsHelper
end

petitions/app/helpers/users_helper.rb
module UsersHelper
end

petitions/app/helpers/votes_helper.rb
module VotesHelper
end

petitions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Петиции" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-brand"><%= link_to "Онлайн петиции", "/" %></div>
    <div class="pull-right" style="margin: 15px">
        <span >
        <% if current_user %>
          <%= current_user.email %>
          <%= link_to "Выйти", log_out_path %>
          <%= link_to "Создать новую петицию", '/petitions/new' %>
          <%= link_to "Мои петиции", petitions_path(my: true)  %>
        <% else %>
          <%= link_to "Зарегистрироваться", sign_up_path %> or 
          <%= link_to "Войти", log_in_path %>
        <% end %>
      </span>
    </div>
  </div>
</div>

<div class="container-fluid">
  <%= flash_messages %>
  <%= yield %>
</div>

</body>
</html>

petitions/app/views/petitions/_my.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Петиция</th>
      <th>Голоса</th>
      <th>Дата создания</th>
      <th>Действия</th>
    </tr>
  </thead>
  <% @petitions.each_with_index do |petition, index| %>
  <tr>
    <td><%= link_to petition.title, "petitions/#{petition.id}" %></td>
    <td><%= petition.votes.count %></td>
    <td><%= petition.created_at.strftime("%d/%m/%Y %H:%M") %></td>
    <td><%= link_to "Редактировать", edit_petition_path(petition)%>
    <%= link_to "Удалить", petition_path(petition), method: :delete, data: { confirm: 'Уверены?' } %></td>
  </tr>
  <% end %>
</table>

petitions/app/views/petitions/edit.html.erb
<div style="margin: 15px">
  <h2>Новая Петиция</h2>
</div>

<%= form_for @petition do |f| %>
 <% if @petition.errors.any? %>

    <div>
      <h2>Form is invalid</h2>
      <ul>
        <% @petition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div style="margin: 15px">
    <div class="form-group" style="width: 40%">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 40%">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control', rows: '6' %>
    </div>
    <div class="actions"><%= submit_tag @petition.new_record? ? 'Cоздать' : 'Сохранить', class: 'btn btn-success' %></div>
  </div>

<% end %>

petitions/app/views/petitions/index.html.erb
<h2><%= params[:my] ? 'Мои' : 'Все' %> петиции</h2>

<% if params[:my] %>
  <%= render "my" %>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Петиция</th>
        <th>Автор</th>
        <th>Голоса</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <% @petitions.each_with_index do |petition, index| %>
    <tr>
      <td><%= link_to petition.title, "petitions/#{petition.id}" %></td>
      <td><%= petition.user.first_name + " " + petition.user.last_name %></td>
      <td><%= petition.votes.count %></td>
      <td><%= petition.created_at.strftime("%d/%m/%Y %H:%M") %></td>
    </tr>
    <% end %>
  </table>
<% end %>

petitions/app/views/petitions/new.html.erb
<div style="margin: 15px">
  <h2>Новая Петиция</h2>
</div>

<%= form_for @petition do |f| %>
  <% if @petition.errors.any? %>

    <div>
      <h2>Form is invalid</h2>
      <ul>
        <% @petition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div style="margin: 15px">
    <div class="form-group" style="width: 40%">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 40%">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control', rows: '6' %>
    </div>
    <div class="actions"><%= submit_tag "Cоздать", class: 'btn btn-default' %></div>
  </div>

<% end %>

petitions/app/views/petitions/show.html.erb
<div style="margin: 15px">
  <h3><%= @petition.title %></h3>
</div>
<div style="margin: 20px">
  <%= @petition.created_at.strftime('%d/%m/%Y %H:%M') %>
</div>
<div style="margin: 30px">
  <%= @petition.text %>
</div>

<p>
  <b>Голосов:</b>
  <%= @petition.votes.count %>
</p>

<p>
  <% if @petition.expired?(@petition.created_at) %>
    Время голосования истекло
  <% elsif @petition.voted_by?(current_user) %>
    Вы уже проголосовали за данную петицию
  <% else %>
    <%= button_to('Поддержать', votes_path({ petition_id: @petition.id }), class: 'btn btn-default' ) %>
  <% end %>
</p>

petitions/app/views/users/new.html.erb
<div style="margin: 15px">
  <h2>Регистрация</h2>
</div>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="margin: 15px">
    <div class="form-group" style="width: 256px">
      <%= f.label :first_name, 'Имя'%><br />
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 256px">
      <%= f.label :last_name, 'Фамилия'%><br />
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 256px">
      <%= f.label :email, 'E-mail' %><br />
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 256px">
      <%= f.label :password, 'Пароль' %><br />
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 256px">
      <%= f.label :password_confirmation, 'Подтверждение пароля' %><br />
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="actions"><%= f.submit "Зарегистрироваться", class: 'btn btn-default' %></div>
  </div>
<% end %>